var AA = null;
var BB = '11';
console.log("typeof CC === 'undefined'", typeof CC === 'undefined');
console.log("typeof AA", typeof AA);
console.log("AA === null", AA === null);
console.log("typeof BB", typeof BB);
console.log("BB === '11'", BB === '11');
console.log("BB == '11'", BB == '11');
console.log("BB === 11", BB === 11);
console.log("BB == 11", BB == 11);
